weekstart: 1
ampmtime: false
dotted: false
calafterschedule: false
addlasthalfhour: false

layout:
  paper:
    width: 15.6cm
    height: 20.9cm

    marginparwidth: 1cm
    marginparsep: 0cm
    reversemargins: true

    margin:
      top: 1.2cm
      bottom: 0.7cm
      left: 0.5cm
      right: 0.5cm

  numbers:
    arraystretch: 1.5                # Controls vertical spacing in tables (LaTeX parameter)
    quarterlylines: 36               # Number of lines in quarterly planning sections
    weeklylines: 11                  # Number of lines in weekly planning sections
    dailytodos: 8                    # Number of todo items in daily pages
    dailynotes: 25                   # Number of note lines in daily pages
    dailypersonal: 6                 # Number of personal items in daily pages
    dailybottomhour: 6               # Starting hour for daily schedule (7 AM)
    dailytophour: 23                 # Ending hour for daily schedule (11 PM)
    dailydiarygoals: 10              # Number of goal lines in daily diary section
    dailydiarygrateful: 4            # Number of gratitude lines in daily diary
    dailydiarybest: 4                # Number of "best things" lines in daily diary
    dailydiarylog: 29                # Number of log lines in daily diary
    todolinesintodopage: 10          # Number of todo lines in dedicated todo pages
    notesindexpages: 3               # Number of pages for notes index
    notesonpage: 35                  # Number of note lines per notes page
    dotheightfull: 36                # Height of dot grid (full page) in units
    dotwidthfull: 30                 # Width of dot grid (full page) in units
    dotwidthtwothirds: 20            # Width of dot grid (2/3 page) in units
    planningstoryrows: 18

  lengths:
    tabcolsep: 3.5pt
    linethicknessdefault: .4pt
    linethicknessthick: .8pt
    lineheightbutline: \dimexpr5mm-.4pt
    twocolsep: 5pt
    tricolsep: 5pt
    fivecolsep: 5pt
    monthlycellheight: 55pt
    notesindexcellheight: 1.37cm
    headerresizebox: 6mm
    headersidequarterswidth: 4cm
    headersidemonthswidth: 14.5cm
    dailyspring: \textcolor{white}{.}

  colors:
    gray: gray
    lightgray: gray!50
